### ISSUE TITLE
Please review ./cc @codepathreview W[2]-Submission

### ISSUE THREAD

**Issue by jch-duran** [jch-duran/Twitter-CodePath#2]
Having difficulties with AutoLayout at the moment and currently working on resolving them. Timestamp as well as incrementation of retweet and favorite have not yet been implemented. I will complete those as well.

**Comment by jch-duran** [comment]
Resolved AutoLayout issues. Moving forward too on timestamp as and incrementation of retweet and favorite.

**Comment by avo1** [comment]
Keep going. We will need to have this completed and updated within **24hr** from the deadline in order for you to receive credit for the assignment.

If you need help with the this function, please reach out to your professional mentors asu slack channel or post to universitysupport@codepath.com

**Comment by jch-duran** [comment]
@avo1 Okay, will do!
